title: "James Ashcroft"
description: "PhD student studying spatial genomics"
url: "https://jashcroft36.github.io"
baseurl: ""

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache
  - jekyll-feed

# Appearance
minimal_mistakes_skin: "dirt"
locale: "en-GB"

# Author
author:
  name: "James Ashcroft"
  avatar: "/assets/img/IMG_1626.jpg"
  location: "Cambridge, UK"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/JAshcroft36"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:ja35@sanger.ac.uk"
