title: "James Ashcroft"
description: "PhD student studying spatial genomics"
url: "https://jashcroft36.github.io"
baseurl: ""

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache
  - jekyll-feed

# Appearance
minimal_mistakes_skin: "default"
locale: "en-GB"

# Author
author:
  name: "James Ashcroft"
  bio: "Genomics PhD Student"
  avatar: "/assets/img/IMG_1626.jpg"
  location: "Cambridge, UK"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/JAshcroft36"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:ja35@sanger.ac.uk"

head_scripts:
  - "<style>
      body {
        font-size: 0.9rem; /* smaller text */
        line-height: 1.5;
      }
      h1, h2, h3 {
        font-size: 90% !important; /* make headings smaller too */
      }
    </style>"
